### ISSUE TITLE
Support for Python>=3.9

### ISSUE THREAD

**Issue by bjhardcastle** [codeocean/codeocean-sdk-python#1]
Hi @zvikagart!

The current requirement for 3.11 or higher is quite limiting: I'd like to use this as a dependency in another package, but need to support lower versions too. In fact, the highest version in a starter environment on our CodeOcean instance is 3.10.

I can't see anything in the dependencies that would require 3.11. And any of the newer typing features are also available via the official backport: https://pypi.org/project/typing-extensions/

Would you be willing to lower this requirement?

I'm happy to test and submit a PR.

**Comment by zvikagart** [comment]
Hi @bjhardcastle,

The package uses [enum.StrEnum](https://docs.python.org/3/library/enum.html#enum.StrEnum) that was added in python 3.11.
We'd be happy to accept PRs to support lower versions.
Thanks!
