### ISSUE TITLE
Allow for retries in requests

### ISSUE THREAD

**Issue by jtyoung84** [codeocean/codeocean-sdk-python#12]
Code Ocean REST API requests will sometimes return a `429` response code when the server is overloaded. It will be helpful if the requests can be set to automatically retry in those events or other server error events.

**Comment by jtyoung84** [comment]
On second thought, it might be better to handle this user-side.

**Comment by zvikagart** [comment]
I think it should be possible to configure the requests session with a retry strategy as described here: https://oxylabs.io/blog/python-requests-retry

```
client = CodeOcean(...)
retry = Retry(...)
adapter = HTTPAdapter(max_retries=retry)
client.session.mount(client.domain, adapter)
```

**Comment by bjhardcastle** [comment]
@zvikagart that looks neat - are you proposing to modify the `CodeOcean` class to allow a requests session to be passed in?

**Comment by zvikagart** [comment]
What I suggested shouldn't require modifications to the package but I haven't tested it.
If you're able to open a PR then allowing to pass in a retry object to the CodeOcean client could be a nice feature.

**Comment by jtyoung84** [comment]
> I think it should be possible to configure the requests session with a retry strategy as described here: https://oxylabs.io/blog/python-requests-retry
> 
> ```
> client = CodeOcean(...)
> retry = Retry(...)
> adapter = HTTPAdapter(max_retries=retry)
> client.session.mount(client.domain, adapter)
> ```

It also requires some extra steps to work without any changes to the source code:
```
client = CodeOcean(...)
retry = Retry(...)
adapter = HTTPAdapter(max_retries=retry)
client.session.mount(client.domain, adapter)
client.capsules = Capsules(client.session)
client.computations = Computations(client.session)
client.data_assets = DataAssets(client.session)
```
